---
- name: Send email with file attachment
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Send email
      command: echo "This is the current host information." | sudo mail -s "Host info" -a /tmp/combined-host-info/current_host_info.txt -r "AnsibleAWX@fleetfarm.com" "andy.adolphson@fleetfarm.com"
